{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Rating",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of book",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "Select title,rate from books",
       "rawQueryText": "Select title,rate from books",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Rate of cds",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "queryText": "Select name,rate from cds",
       "rawQueryText": "Select name,rate from cds",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Rate of electronics",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 11, "x": 7, "y": 9 },
     "targets": [
      {
       "queryText": "Select name,rate from electronics",
       "rawQueryText": "Select name,rate from electronics",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  { "title": "Stock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Global quantity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 6, "y": 2 },
   "targets": [
    {
     "queryText": "SELECT type, SUM(quantity) AS total_stock\nFROM (\n    SELECT 'books' AS type, quantity FROM books\n    UNION ALL\n    SELECT 'cds' AS type, quantity FROM cds\n    UNION ALL\n    SELECT 'electronics' AS type, quantity FROM electronics\n) AS all_products\nGROUP BY type;\n",
     "rawQueryText": "SELECT type, SUM(quantity) AS total_stock\nFROM (\n    SELECT 'books' AS type, quantity FROM books\n    UNION ALL\n    SELECT 'cds' AS type, quantity FROM cds\n    UNION ALL\n    SELECT 'electronics' AS type, quantity FROM electronics\n) AS all_products\nGROUP BY type;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Electronics quantity",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT name, quantity from electronics",
     "rawQueryText": "SELECT name, quantity from electronics"
    }
   ]
  },
  {
   "title": "Book quantity",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT title, quantity FROM books",
     "rawQueryText": "SELECT title, quantity FROM books",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Cds quantity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 17 },
   "targets": [
    {
     "queryText": "SELECT name,quantity from cds",
     "rawQueryText": "SELECT name,quantity from cds",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Sell",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total of sell",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 3 },
     "targets": [
      {
       "queryText": "SELECT type, SUM(sell) AS total_stock\nFROM (\n    SELECT 'books' AS type, sell FROM books\n    UNION ALL\n    SELECT 'cds' AS type, sell FROM cds\n    UNION ALL\n    SELECT 'electronics' AS type, sell FROM electronics\n) AS all_products\nGROUP BY type;\n",
       "rawQueryText": "SELECT type, SUM(sell) AS total_stock\nFROM (\n    SELECT 'books' AS type, sell FROM books\n    UNION ALL\n    SELECT 'cds' AS type, sell FROM cds\n    UNION ALL\n    SELECT 'electronics' AS type, sell FROM electronics\n) AS all_products\nGROUP BY type;\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Books sold",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "queryText": "SELECT sell, title from books",
       "rawQueryText": "SELECT sell, title from books",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "electronics sold",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "queryText": "SELECT sell, name from electronics",
       "rawQueryText": "SELECT sell, name from electronics",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "cds sold",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 7, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "queryText": "SELECT sell, name from cds",
       "rawQueryText": "SELECT sell, name from cds",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  }
 ]
}